/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "led.h"
#include "button.h"
#include "usart2.h"
#include "adc.h"
#include "systick.h"
#include "tim.h"
#include "exti.h"
#include "dma.h"
#include "adxl345.h"

#include "stdint.h"
#include "stdio.h"
#include "string.h"
#include "stm32f3xx.h"

static void led_button(void);
static void led_uart_command(void);
static void led_systick(void);
static void led_tim(void);
static uint32_t tim3_pa6_input_capture(void);
static void adxl_measure(void);

const char* const test_msg = "Hello from ST DMA TX !\r\n";

int main(void)
{
	//led_init();
	usart2_init();
	//dma_usart2_init((uint32_t)test_msg, (uint32_t)&USART2->TDR, strlen(test_msg));
	//exti_pc13_init();
	//systick_1sec_interrupt_init();
	//button_init();
	//adc_init();
	//tim2_sec_interrupt_init();
	//tim2_pa5_output_compare_init();
	//tim3_pa6_input_capture_init();
	adxl_init();
	for(;;){
		adxl_measure();
	}
}

static void adxl_measure(void){
	int16_t x,y,z;
	uint8_t rx_data[6];

	adxl_read(DATA_START_ADDR_R, rx_data);

	x = ((rx_data[1]<<8)|rx_data[0]);
	y = ((rx_data[3]<<8)|rx_data[2]);
	z = ((rx_data[5]<<8)|rx_data[4]);

	printf("X: %d, Y: %d, Z: %d \r\n", x, y, z);
}

static uint32_t tim3_pa6_input_capture() {
	//Connect jumper wire between PA5 and PA6 in order to capture output toggle
	while(!(TIM3->SR & TIM_SR_CC1IF)) ;
	uint32_t timestamp = TIM3->CCR1;
	printf("Captured: %u\r\n", timestamp);
	return timestamp;
}

static void led_tim(void){
	while(!(TIM2->SR & TIM_SR_UIF)) ;
	TIM2->SR &= ~TIM_SR_UIF;

	printf("A second has passed !\r\n");
	led_toggle();
}

static void led_systick(void){
	systick_delay_ms(500);
	led_toggle();
	systick_delay_ms(1000);
	led_toggle();
}

void led_button(void) {
	if( button_is_pressed())
		led_set(true);
	else
		led_set(false);
}

void led_uart_command(void){
	char key = usart2_read();
	if( key == '1' )
		led_set(true);
	else if(key == '0')
		led_set(false);
}
